#!/usr/bin/env python3

import json
import os
import sys

def print_help():
  first_arg = sys.argv[1]
  if first_arg == '-h' or first_arg == '--help':
    print("""
Help: %s

Arguments: <path/to/dir>

Options:
  -h, --help: Prints this message
""" % (os.path.basename(sys.argv[0])))
    exit(0)

print_help()

def is_not_selection(selection):
  return selection[0] == '!'

def format_entry(root, entry):
  config = entry.split(':')
  if len(config) != 2: raise ValueError(f"Bad configuration: expecting '<base path>:<spec> but got {entry}")

  [path, selection] = config
  expanded = os.path.expanduser(path)
  if not os.path.isabs(expanded):
    expanded = os.path.normpath(os.path.join(os.getcwd(), root, expanded))
  
  return (expanded, selection) 

def check_entries(entries):
  for (e, f) in entries:
    if not os.path.isdir(e):
      raise RuntimeError(f"Base folder {e} is not a directory")

    if not is_not_selection(f):
      source_dir = os.path.join(e, f)
      if not os.path.isdir(source_dir):
        raise RuntimeError(f"Lego entry {source_dir} is not a directory")

def build_entries(virtual_dir, entries):
  for (parent_dir, selection) in entries:
    if is_not_selection(selection):
      create_not_entries(virtual_dir, parent_dir, selection)
    else:
      create_entry(virtual_dir, parent_dir, selection)

def create_hierarchy(root_dir, folder):
  current_path = root_dir
  remaining = folder
  while True:
    (head, remaining) = os.path.split(remaining)
    if len(head) == 0: break
    
    current_path = os.path.join(current_path, head)
    if not os.path.exists(current_path):
      os.mkdir(current_path)

def create_entry(virtual_dir, parent_dir, folder):
  target_dir = os.path.join(virtual_dir, folder)
  if os.path.exists(target_dir):
    print(f"{target_dir} already present. Skipping ...")
  else:
    base_dir = os.path.dirname(folder)
    if len(base_dir) > 0:
      create_hierarchy(virtual_dir, folder)
    
    source_dir = os.path.join(parent_dir, folder)
    os.symlink(source_dir, target_dir)

def create_not_entries(virtual_dir, parent_dir, folder):
  unwanted = folder[1:]
  elements = os.listdir(parent_dir)
  check = lambda e: e != unwanted and e[0] != '.' and os.path.isdir(os.path.join(parent_dir, e))
  for e in elements:
    if check(e):
      create_entry(virtual_dir, parent_dir, e)

virtual_dir_path = sys.argv[1]

with open(os.path.join(virtual_dir_path, '.lego-spec')) as file:
  config = json.load(file)

entries = [format_entry(virtual_dir_path, e.strip()) for e in config['structure']]
print(entries)

check_entries(entries)
build_entries(virtual_dir_path, entries)
