#!/usr/bin/env python3

import json
import os
import sys

import v1
import fs

def print_help():
  first_arg = sys.argv[1]
  if first_arg == '-h' or first_arg == '--help':
    print("""
Help: %s

Arguments: <path/to/dir>

Options:
  -h, --help: Prints this message
""" % (os.path.basename(sys.argv[0])))
    exit(0)

print_help()

def get_version(config):
  if 'version' in config:
    return config['version']
  else:
    return 1

virtual_dir_path = sys.argv[1]

with open(os.path.join(virtual_dir_path, '.lego-spec')) as file:
  config = json.load(file)

version = get_version(config)
if version == 1:
  v1.process_structure(virtual_dir_path, config['structure'], fs.SYSTEM)
elif version == 2:
  raise RuntimeError("Work in progress for this version")
else:
  raise RuntimeError(f"Unsupported version {version}")
