#!/bin/bash

function run_tests() {
	python3 -m unittest *_test.py && ./lego-dir --help > /dev/null
}

function commit() {
	git commit -am "working"
	echo -e "\e[32m"
	cat << MSG
 _  _  _____  __  __    ____  _____   ___  _  _   /\\
( \/ )(  _  )(  )(  )  (  _ \(  _  ) / __)( )/ )  )(
 \  /  )(_)(  )(__)(    )   / )(_)( ( (__  )  (   \/
 (__) (_____)(______)  (_)\_)(_____) \___)(_)\_)  ()
MSG
	echo -e "\e[0m"
}

function revert() {
	git reset --hard HEAD
	git clean -fd
	echo -e "\e[31mOops\e[0m You got reverted!!"
}

while true
do
	read -p 'Press enter if you feel lucky...' y
	run_tests && commit || revert
done